name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Esquetta
          BRANCH_NAME: main
          UTC_OFFSET: 3
          EXCLUDE: ""
          AUTO_PUSH: true
